### ISSUE TITLE
PubMed-w2v.bin missing

### ISSUE THREAD

**Issue by freesinger** [jayded/evidence-inference#13]
Hi,
First of all, impressive paper and nice codes.
I'm trying to reproducing paper results by run `./scripts/paper/final_experiments_all.sh`, which come into the problem `FileNotFoundError: [Errno 2] No such file or directory: 'embeddings/PubMed-w2v.bin'`.
It seems the pre-trained PubMed embeddings are not provided, could you please send me the bin file or tell me where I could fetch the exact file I need?
Thank you!

**Comment by jayded** [comment]
This is documented in https://github.com/jayded/evidence-inference/blob/master/SETUP.md

Thanks for your interest.
