### ISSUE TITLE
xml files for new bigger dataset

### ISSUE THREAD

**Issue by zenhub-nr** [jayded/evidence-inference#15]
Hi, can you provide a download link for the nxml files for the 2nd version of the dataset? The txt files have some issues (some txt files are blank).

**Comment by jayded** [comment]
Oops! I need to merge the ei2.0 branch; I need to double check a couple things and do some house keeping, but the files are there:
https://github.com/jayded/evidence-inference/tree/ei2.0prerelease/annotations/xml_files

**Comment by zenhub-nr** [comment]
Ohh okay thanks!
