### ISSUE TITLE
Can I, C, O be mapped back to the original article?

### ISSUE THREAD

**Issue by drqiaojin** [jayded/evidence-inference#3]
Dear developers,

How do you collect I, C, O? Is it extractive so that they can be mapped back to the original articles, or abstractive?

Thanks,
Qiao

**Comment by jayded** [comment]
In general, no this isn't possible. Longer answer: sometimes.

This seems like it's partially documented (you'd have to read https://github.com/jayded/evidence-inference/blob/master/README.annotation_process.md#process-description and then watch @elehman16 's video in http://www.ccs.neu.edu/home/lehmer16/prompt-gen-instruction/templates/instructions.html ; we could make that more obvious). When annotators are generating prompts they the option of:
1. directly copying text for each field
2. copying an existing prompt (and one or more fields)
3. typing their own versions of the I,C,O.

It's this third option that's most problematic. Sometimes this is necessary, but not always. It's my sense from looking at the data that directly copying is fairly common, so this could sometimes be done via a `str.find`. The annotators are directed not to always copy from the document so some are guaranteed to be abstractive (I don't have a proportion available).

We have not recorded any kind of offsets for case (1) or (2), so we can't transform these into anything abstractive.

**Comment by drqiaojin** [comment]
@jayded Hi Jay, thanks a lot for your prompt and thorough reply.

We noticed that a previous work of PICO extraction of your group formulates such task as identifying text spans in RCT abstracts. Though abstractive I, C, Os are more precise than extractive ones in some cases, such setting makes it harder to train an end-to-end system that can take as input the whole article and output all prompts with their changes and the evidence on this dataset.

**Comment by bwallace** [comment]
Hi Qiao, thanks for your interest in the corpus! So we intentionally wanted to allow physicians to specify I, C and Os 'naturally' for the sake of this task. That said, we are of course also ultimately interested in an end to end system, and are presently working on collecting such annotations.

**Comment by drqiaojin** [comment]
@bwallace Hi Dr. Wallace, thanks for the reply. This intention makes sense and annotations for training end to end systems will be very useful!
